---
title: "salamander-and-cutthroat-analysis"
format: html
---

```{r}
library(tidyverse)
library(here)
library(janitor)
#| warning: false
#| echo: false
```
```{r}
mack_verts <- read_csv(here::here("data", "AS00601.csv"))

mack_verts <- mack_verts %>% janitor::clean_names()
```

```{r}
mc_wt_5 <- mack_verts[5, "weight"]
mc_length_8_20 <- mack_verts[8:20, "length1"]
mc_dates <- mack_verts[,"sampledate"]
```

```{r}
mc_salamanders <- dplyr::filter(mack_verts, species == "DITE")
```

```{r}
#| warning: false
#| echo: false

mc_salamander_plot <- ggplot(data = mc_salamanders, 
  aes(x = length1, y = weight))+
  geom_jitter()+ 
  labs(title = "Salamander Size",
  x = "Snout-Vent Length (mm)",
  y = "Weight (g)")

mc_salamander_plot

ggsave(here::here("figs", "salamander_size.png"))
```

```{r}
#| warning: false
#| echo: false
mc_trout <- dplyr::filter(mack_verts, species == "ONCL")
cutthroat_size <- ggplot(data = mc_trout, 
  aes(x = length1, y = weight))+
  geom_jitter(aes(color = reach))+
  scale_color_manual(values = c("navy", "hotpink", "darkgreen"))+
  facet_wrap(vars(reach))+
  labs(title = "Trout Size",
  x = "Snout-Vent Length (mm)",
  y = "Weight (g)")


cutthroat_size

ggsave(here::here("figs", "cutthroat_size.png"))
```

